sudo: false
language: python

python:
  - 3.6

env:
  global:
    - DJANGO="2.0.2"
    - DJANGO_SETTINGS_MODULE="umami.settings"
    - PIP_USE_MIRRORS=true
    - DATABASE_URL=sqlite:///db.sqlite3

cache:
  directories:
    - $HOME/.cache/pip

install:
    - pip install -r requirements.txt
    - pip install pytest pytest-django pytest-cov
    - pip install coveralls

script:
    - python manage.py migrate --noinput
    - python manage.py collectstatic --noinput
    - pytest --cov umami --cov guildmaster

after_success: coveralls

notifications:
    email:
        on_success: change
        on_failure: always
